agent_services: []
search_services: []
other_services:
  object_manager: True
  query_manager: True
  semantic_manager: False
sql_statement_permissions:
  - Alter: False
  - Command: True
  - Comment: True
  - Commit: False
  - Create: False
  - Delete: False
  - Describe: True
  - Drop: False
  - Insert: False
  - Merge: False
  - Rollback: False
  - Select: True
  - Transaction: False
  - TruncateTable: False
  - Unknown: False
  - Update: False
  - Use: False